#-------------------------------------------------------------------------------
# Name:        Problem 2
# Purpose:
#       Each new term in the Fibonacci sequence is generated by 
#       adding the previous two terms. By starting with 1 and 2, 
#       the first 10 terms will be:
#
#               1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#       By considering the terms in the Fibonacci sequence whose 
#       values do not exceed four million, find the sum of 
#       the even-valued terms.
#
# Link: http://projecteuler.net/index.php?section=problems&id=2
# Author:      brlv
#-------------------------------------------------------------------------------
#!/usr/bin/env python

def main():
    a, b = 1, 1
    total = 0
    while a < 4000000:
        a, b = b, a+b
        a, b = b, a+b
        total += a
        a, b = b, a+b

    print total

if __name__ == '__main__':
    main()